vars:
  - code_dir: src/probafcst/
  - pipe_dir: src/probafcst/pipeline

stages:
  prepare:
    foreach:
      - energy
      - bikes
    do:
      cmd: python ${pipe_dir}/prepare.py --target ${item}
      params:
        - data.${item}
        - cache
      deps:
        - ${pipe_dir}/prepare.py
        - ${code_dir}/data.py
      outs:
        - data/${item}.parquet
  train:
    foreach:
      - energy
      - bikes
    do:
      cmd: python ${pipe_dir}/train.py --target ${item}
      params:
        - data.${item}
        - train.${item}
        - quantiles
      deps:
        - data/${item}.parquet
        - ${pipe_dir}/train.py
        - ${code_dir}/models/
        - ${code_dir}/utils/tabularization.py
      outs:
        - models/${item}_model.pkl
  eval:
    foreach:
      - energy
      - bikes
    do:
      cmd: python ${pipe_dir}/evaluate.py --target ${item}
      params:
        - eval
      deps:
        - data/${item}.parquet
        - models/${item}_model.pkl
        - ${pipe_dir}/evaluate.py
        - ${code_dir}/plotting.py
        - ${code_dir}/backtest.py
        - ${code_dir}/utils/tabularization.py
        - ${code_dir}/metrics/

      outs:
        - output/${item}_eval_results.csv
      plots:
        - output/eval_plots/${item}/
        - output/${item}_pinball_losses.svg
      metrics:
        - output/${item}_metrics.json
  submit:
    cmd: python ${pipe_dir}/submit.py
    params:
      - quantiles
    deps:
      - ${pipe_dir}/submit.py
      - ${code_dir}/utils/check_submission.py
      - ${code_dir}/utils/create_submission.py
      - ${code_dir}/plotting.py
      - models/energy_model.pkl
      - models/bikes_model.pkl
    outs:
      - output/submission.csv
    plots:
      - output/energy_forecast.svg
      - output/bikes_forecast.svg
