cache:
  enable: true
  days_expire_after: 5

data_dir: data
model_dir: models
output_dir: output

quantiles:
- 0.025
- 0.25
- 0.5
- 0.75
- 0.975

data:
  bikes:
    filename: bikes.parquet
    start_date: '2012-04-25'
    freq: D
    target_col: bike_count
    weather_features:
     - temperature_2m_max
     - temperature_2m_min
     - daylight_duration
     - sunshine_duration
     - precipitation_sum
     - wind_speed_10m_max
  no2:
    filename: no2.parquet
    start_date: '2016-01-01'
    end_date: '2024-10-26'
    freq: h
  energy:
    filename: energy.parquet
    ignore_years: 0
    freq: h
    target_col: load
    weather_features:
      # - temperature_2m
      # - relative_humidity_2m
      # - precipitation
      # - cloud_cover
      # - wind_speed_100m
      # - is_day
      # - sunshine_duration

train:
  bikes:
    selected: lgbm
    cutoff: '2021-11-14' # use only data onwards this date for training the final model
    benchmark:
      n_weeks: 100

    quantreg:
      kwargs:
        solver: highs-ipm
      lags:
        - 1
        - 2
        - 7
        - 14
      include_seasonal_dummies: true
      cyclical_encodings: true
      X_lag_cols: null

    xgboost:
      freq: D
      output_chunk_length: 7
      xgb_kwargs:
        n_jobs: -1
    xgb-custom:
      lags:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 14
      include_seasonal_dummies: true
      cyclical_encodings: true
      X_lag_cols: null
      kwargs:
        n_jobs: -1
        random_state: 0
        # early_stopping_rounds: 50
        # n_estimators: 1000
        # learning_rate: 0.05
        # subsample: 0.8
        # colsample_bytree: 0.8
    lgbm:
      lags:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 14
      include_seasonal_dummies: true
      cyclical_encodings: true
      X_lag_cols:
        - precipitation_sum
      kwargs:
        n_jobs: -1
        verbose: -1
        random_state: 0
    catboost:
      lags:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 14
      include_seasonal_dummies: true
      cyclical_encodings: true
      X_lag_cols: null
      kwargs:
        n_estimators: 100
        verbose: 0
        random_state: 0


  energy:
    selected: lgbm
    cutoff: '2021-11-14'
    benchmark:
      n_weeks: 100

    quantreg:
      kwargs:
        solver: highs-ipm
      lags:
        - 24
        - 48
        - 168
      include_seasonal_dummies: true
      cyclical_encodings: true
      X_lag_cols: null

    xgboost:
      freq: h
      output_chunk_length: 24
      xgb_kwargs:
        n_jobs: -1

    xgb-custom:
      lags:
        - 24
        - 48
        - 72
        - 96
        - 120
        - 144
        - 168
        - 336 # 2 weeks
        - 504 # 3 weeks
        - 672
      include_seasonal_dummies: true
      cyclical_encodings: true
      X_lag_cols: null
      kwargs:
        n_jobs: -1
        random_state: 0
        # early_stopping_rounds: 50
        # n_estimators: 1000
        # learning_rate: 0.05
        # subsample: 0.8
        # colsample_bytree: 0.8
    lgbm:
      lags:
        - 24
        - 48
        - 72
        - 96
        - 120
        - 144
        - 168
        - 336 # 2 weeks
        - 504 # 3 weeks
        - 672
      include_seasonal_dummies: true
      cyclical_encodings: true
      X_lag_cols: null
      kwargs:
        n_jobs: -1
        verbose: -1
        random_state: 0

    catboost:
      lags:
        - 24
        - 48
        - 72
        - 96
        - 120
        - 144
        - 168
        - 336
        - 504 # 3 weeks
        - 672

      include_seasonal_dummies: true
      cyclical_encodings: true
      X_lag_cols: null
      kwargs:
        n_estimators: 100
        random_state: 0
        verbose: 0

eval:
  backend: loky # null or 'loky' for parallel evaluate
  splitter_type: sliding # or expanding
  bikes:
    forecast_steps_days: 7
    # for sliding windows, this determines the window length in years (train size)
    n_years_initial_window: 3
    step_length_days: 30
  energy:
    forecast_steps_days: 7
    n_years_initial_window: 3
    step_length_days: 90
