cache:
  enable: true
  days_expire_after: 5

data_dir: data
model_dir: models
output_dir: output

quantiles:
- 0.025
- 0.25
- 0.5
- 0.75
- 0.975
data:
  bikes:
    filename: bikes.parquet
    start_date: '2012-04-25'
    freq: D
    target_col: bike_count
    weather_features:
    - temperature_2m_max
    - temperature_2m_min
    - daylight_duration
    - sunshine_duration
    - precipitation_sum
  no2:
    filename: no2.parquet
    start_date: '2016-01-01'
    end_date: '2024-10-26'
    freq: h
  energy:
    filename: energy.parquet
    ignore_years: 0
    freq: h
    target_col: load
    weather_features:
      # - temperature_2m
      # - relative_humidity_2m
      # - precipitation
      # - cloud_cover
      # - wind_speed
      # - is_day
      # - sunshine_duration

train:
  bikes:
    selected: benchmark
    cutoff: '2012-10-23' # use only data onwards this date for training the final model
    benchmark:
      n_weeks: 100

    quantreg:
      kwargs:
        solver: highs-ipm
      lags:
      - 7
      - 14
      include_seasonal_dummies: true
      include_rolling_stats: false
      cyclical_encodings: false
      X_lag_cols: []

    xgboost:
      freq: D
      output_chunk_length: 7
      xgb_kwargs:
        n_jobs: -1
    xgb-custom:
      lags:
      - 1
      - 2
      - 6
      - 7
      - 14
      - 21
      - 28
      include_seasonal_dummies: true
      cyclical_encodings: true
      include_rolling_stats: false
      X_lag_cols:
      kwargs:
        n_jobs: -1
        random_state: 0
        n_estimators: 250
        tree_method: hist
        grow_policy: depthwise
        learning_rate: 0.1
        max_depth: 6
        colsample_bylevel: 0.6
        subsample: 0.9
        min_split_gain: 1e-3
        reg_lambda: 1e-3
    lgbm:
      lags:
      - 1
      - 2
      - 6
      - 7
      - 8
      - 14
      - 21
      - 28
      include_seasonal_dummies: true
      cyclical_encodings: true
      include_rolling_stats: false
      X_lag_cols:
      kwargs:
        n_jobs: -1
        verbose: -1
        random_state: 0
        num_leaves: 15
        min_child_samples: 50
        n_estimators: 250
        max_depth: 9
        learning_rate: 0.1
        reg_lambda: 1
        colsample_bytree: 0.6
        subsample_freq: 1
        subsample: 0.9

    catboost:
      lags:
      - 1
      - 2
      - 6
      - 7
      - 14
      - 21
      - 28
      include_seasonal_dummies: true
      cyclical_encodings: true
      include_rolling_stats: false
      X_lag_cols:
      kwargs:
        thread_count: -1
        learning_rate: 0.1
        n_estimators: 250 # default: 1000
        verbose: 0
        random_state: 0
        max_depth: 6 # default: 6
        boosting_type: Plain # default: Ordered
        reg_lambda: 1e-2
        grow_policy: SymmetricTree # the default
        colsample_bylevel: 0.6
        subsample: 0.9

    qrf:
      lags:
      - 1
      - 2
      - 3
      - 7
      - 14
      - 21
      include_seasonal_dummies: true
      cyclical_encodings: true
      include_rolling_stats: false
      X_lag_cols: []
      kwargs:
        n_estimators: 100
        random_state: 0
        n_jobs: -1



  energy:
    selected: benchmark
    cutoff: '2015-10-23'
    benchmark:
      n_weeks: 100

    quantreg:
      kwargs:
        solver: highs-ipm
      lags:
      - 168
      include_seasonal_dummies: true
      include_rolling_stats: false
      cyclical_encodings: false
      X_lag_cols: []

    xgboost:
      freq: h
      output_chunk_length: 24
      xgb_kwargs:
        n_jobs: -1

    xgb-custom:
      lags:
      - 24
      - 48
      - 72
      - 96
      - 120
      - 144
      - 168
      - 336
      - 504
      - 672
      include_seasonal_dummies: true
      cyclical_encodings: true
      X_lag_cols:
      kwargs:
        n_jobs: -1
        random_state: 0
        n_estimators: 250
        tree_method: hist
        grow_policy: depthwise
        learning_rate: 0.1
        max_depth: 6
        colsample_bylevel: 0.6
        subsample: 0.8
        min_split_gain: 1e-3
        reg_lambda: 1e-3

    lgbm:
      lags:
      - 24
      - 48
      - 72
      - 96
      - 120
      - 144
      - 168
      - 336
      - 504
      - 672
      include_seasonal_dummies: true
      cyclical_encodings: true
      X_lag_cols:
      include_rolling_stats: false
      kwargs:
        n_jobs: -1
        verbose: -1
        random_state: 0
        num_leaves: 20
        min_child_samples: 200
        n_estimators: 250
        max_depth: 12
        learning_rate: 0.1
        subsample_freq: 1
        subsample: 0.8
        reg_lambda: 2
        colsample_bytree: 0.6

    catboost:
      lags:
      - 24
      - 48
      - 72
      - 96
      - 120
      - 144
      - 168
      - 336
      - 504
      - 672
      include_seasonal_dummies: true
      cyclical_encodings: true
      include_rolling_stats: false
      X_lag_cols:
      kwargs:
        thread_count: -1
        learning_rate: 0.1
        n_estimators: 250
        random_state: 0
        verbose: 0
        max_depth: 6
        boosting_type: Plain # default: Ordered (much slower and performs worse here)
        reg_lambda: 1e-2
        grow_policy: SymmetricTree
        colsample_bylevel: 0.6
        subsample: 0.8

    qrf:
      lags:
      - 24
      - 48
      - 72
      - 96
      - 120
      - 144
      - 168
      - 336
      - 504
      - 672
      include_seasonal_dummies: true
      cyclical_encodings: true
      X_lag_cols: []
      include_rolling_stats: false
      kwargs:
        n_estimators: 100
        random_state: 0
        n_jobs: -1

eval:
  backend: loky # null or 'loky' for parallel evaluate
  splitter_type: sliding # or expanding
  eval_start: '2023-10-23'
  eval_end: '2024-10-23'
  bikes:
    forecast_steps_days: 7
    step_length_days: 7
  energy:
    forecast_steps_days: 7
    step_length_days: 7
