cache:
  enable: true
  days_expire_after: 5

data_dir: data
model_dir: models
output_dir: output

quantiles:
  - 0.025
  - 0.25
  - 0.5
  - 0.75
  - 0.975

data:
  bikes:
    filename: bikes.parquet
    start_date: '2012-04-25'
  no2:
    filename: no2.parquet
    start_date: '2016-01-01'
    end_date: '2024-10-26'
  energy:
    filename: energy.parquet
    ignore_years: 0

eval:
  bikes:
    fh: 31 # 1 month
    initial_window: 730 # 365 * 2
    step_length: 150
  energy:
    fh: 168 # 1 week
    initial_window: 26280 # 3 years
    step_length: 8760
